name: DynamicShop
version: ${project.version}
main: me.sat7.dynamicshop.DynamicShop
depend: [Vault, AldarEconomy]
softdepend: [PlaceholderAPI, Jobs]
api-version: 1.13
authors: [sat7]
description: Full GUI shop with dynamic prices
commands:
  DynamicShop:
    description: "Full GUI shop with dynamic prices"
    aliases: [ds]
  shop:
